input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "logstash-internal"
    password => "123456"
    index => "logs-%{+YYYY.MM.dd}"
    manage_template => false
  }
}
